version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: offboarding_postgres
    ports:
      - "5803:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
      POSTGRES_DB: offboarding_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: offboarding_backend
    ports:
      - "3031:3031"
    environment:
      DB_NAME: offboarding_db
      DB_PORT: 5432
    depends_on:
      - postgres

  employee-offboarding:
    build: ./employee-offboarding
    container_name: offboarding_employee_ui
    ports:
      - "8045:80"

  hr-offboarding:
    build: ./hr-offboarding
    container_name: offboarding_hr_ui
    ports:
      - "8046:80"

volumes:
  pgdata:

